# Generated by Django 2.1.5 on 2019-01-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='image',
            field=models.FileField(default='media/documents/dog.jpg', upload_to='documents/'),
        ),
    ]
