# Generated by Django 2.1.5 on 2019-01-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_App', '0002_expenses_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='creator',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='image',
            field=models.FileField(default='media/documents/dog.jpg', null=True, upload_to='documents/'),
        ),
    ]
