# Generated by Django 2.1.5 on 2019-01-29 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Expense_App', '0005_remove_expenses_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
