# Generated by Django 2.1.5 on 2019-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_App', '0006_expenses_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='image',
            field=models.ImageField(default='media/documents/dog.jpg', null=True, upload_to='documents/'),
        ),
    ]
